apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    sonarqube.org/project-key: React-Test
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
