apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata: 
  description: "Create a new CRA website project"
  name: create-react-app-template
  tags: 
    - react
    - cra
  title: "Create React App Template"
spec: 
  output: 
    links: 
      - 
        title: Repository
        url: "${{ steps.publish.output.remoteUrl }}"
      - 
        entityRef: "${{ steps.register.output.entityRef }}"
        icon: catalog
        title: "Open in catalog"
  owner: "user:guest"
  parameters: 
    - 
      properties: 
        name: 
          description: "Unique name of the component"
          title: Name
          type: string
          ? "ui:autofocus"
          : true
          ? "ui:options"
          : 
            rows: 5
      required: 
        - name
      title: "Provide some basic information"
    - 
      properties: 
        repoUrl: 
          title: "Repository Location"
          type: string
          ? "ui:field"
          : RepoUrlPicker
          ? "ui:options"
          : 
            allowedHosts: 
              - github.com
      required: 
        - repoUrl
      title: "Choose a location"
    - 
      properties: 
        repoUrl: 
          title: "Repository Location"
          type: string
          ? "ui:field"
          : RepoUrlPicker
          ? "ui:options"
          : 
            allowedHosts: 
              - github.com
      required: 
        - repoUrl
      title: "Choose a location"
  steps: 
    - 
      action: "fetch:template"
      id: fetch-base
      input: 
        url: ./template
        values: 
          name: "${{ parameters.name }}"
      name: "Fetch Base"
    - 
      action: "publish:github"
      id: publish
      input: 
        allowedHosts: 
          - github.com
        description: "This is ${{ parameters.name }}"
        repoUrl: "${{ parameters.repoUrl }}"
      name: Publish
    - 
      action: "catalog:register"
      id: register
      input: 
        catalogInfoPath: /catalog-info.yaml
        repoContentsUrl: "${{ steps.publish.output.repoContentsUrl }}"
      name: Register
  type: service
